[package]
name = "snarkvm-synthesizer-program"
version = "3.8.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Program for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
serial = [ "snarkvm-console/serial" ]
wasm = [ "snarkvm-console/wasm" ]

[dependencies.snarkvm-circuit]
workspace = true

[dependencies.snarkvm-console]
workspace = true
default-features = false
features = [ "account", "network", "program", "types" ]

[dependencies.indexmap]
workspace = true
features = [ "serde", "rayon" ]

[dependencies.paste]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.rand_chacha]
workspace = true

[dependencies.serde_json]
workspace = true
features = [ "preserve_order" ]

[dependencies.snarkvm-synthesizer-snark]
workspace = true

[dev-dependencies.bincode]
workspace = true

[dev-dependencies.snarkvm-console]
workspace = true
features = [ "test", "default" ]

[dev-dependencies.criterion]
workspace = true

[dev-dependencies.snarkvm-synthesizer-process]
workspace = true
